//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestCloud.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("InvestCloud.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GreenField {
            get {
                return ResourceManager.GetString("GreenField", resourceCulture);
            }
        }
        
        internal static string GetStartedTitle {
            get {
                return ResourceManager.GetString("GetStartedTitle", resourceCulture);
            }
        }
        
        internal static string GetStartedDescription {
            get {
                return ResourceManager.GetString("GetStartedDescription", resourceCulture);
            }
        }
        
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        internal static string LoginBackToYourAccount {
            get {
                return ResourceManager.GetString("LoginBackToYourAccount", resourceCulture);
            }
        }
        
        internal static string EnterYourUsername {
            get {
                return ResourceManager.GetString("EnterYourUsername", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string DoNotHaveAnAccount {
            get {
                return ResourceManager.GetString("DoNotHaveAnAccount", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string EnterPersonalInfo {
            get {
                return ResourceManager.GetString("EnterPersonalInfo", resourceCulture);
            }
        }
        
        internal static string EnterYourFirstName {
            get {
                return ResourceManager.GetString("EnterYourFirstName", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string EnterYourLastName {
            get {
                return ResourceManager.GetString("EnterYourLastName", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string EnterYourPhoneNumber {
            get {
                return ResourceManager.GetString("EnterYourPhoneNumber", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string ServiceStartDate {
            get {
                return ResourceManager.GetString("ServiceStartDate", resourceCulture);
            }
        }
        
        internal static string ServiceStartDateErrorText {
            get {
                return ResourceManager.GetString("ServiceStartDateErrorText", resourceCulture);
            }
        }
        
        internal static string FirstNameErrorText {
            get {
                return ResourceManager.GetString("FirstNameErrorText", resourceCulture);
            }
        }
        
        internal static string LastNameErrorText {
            get {
                return ResourceManager.GetString("LastNameErrorText", resourceCulture);
            }
        }
        
        internal static string PasswordMinAndMaxCharErrorText {
            get {
                return ResourceManager.GetString("PasswordMinAndMaxCharErrorText", resourceCulture);
            }
        }
        
        internal static string PasswordOneLowerCaseErrorText {
            get {
                return ResourceManager.GetString("PasswordOneLowerCaseErrorText", resourceCulture);
            }
        }
        
        internal static string PasswordOneUpperCaseErrorText {
            get {
                return ResourceManager.GetString("PasswordOneUpperCaseErrorText", resourceCulture);
            }
        }
        
        internal static string PasswordRepetitiveErrorText {
            get {
                return ResourceManager.GetString("PasswordRepetitiveErrorText", resourceCulture);
            }
        }
        
        internal static string PhoneNumberErrorText {
            get {
                return ResourceManager.GetString("PhoneNumberErrorText", resourceCulture);
            }
        }
        
        internal static string AccountNotExistsError {
            get {
                return ResourceManager.GetString("AccountNotExistsError", resourceCulture);
            }
        }
        
        internal static string PasswordNotMatchError {
            get {
                return ResourceManager.GetString("PasswordNotMatchError", resourceCulture);
            }
        }
        
        internal static string SuccessAuthenticationMessage {
            get {
                return ResourceManager.GetString("SuccessAuthenticationMessage", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string SignInNow {
            get {
                return ResourceManager.GetString("SignInNow", resourceCulture);
            }
        }
        
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordTappedMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordTappedMessage", resourceCulture);
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
    }
}
